name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  packages: read

jobs:
  deploy:
    name: Mock Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME || github.actor }}
          password: ${{ secrets.GHCR_TOKEN || github.token }}

      - name: Define image tag
        id: vars
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/sample_app:${{ github.event.workflow_run.head_branch || 'main' }}-${{ github.event.workflow_run.head_sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Pull image
        run: docker pull ${{ env.IMAGE }}

      - name: Mock deployment (run container)
        run: |
          echo "Running mock deployment..."
          docker run --rm ${{ env.IMAGE }} 2 3

      - name: Comment PR
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "CD Summary"
          message: |
            **Mock Deployment completed successfully**

            - Docker image: `${{ env.IMAGE }}`
            - Command: `docker run --rm ${{ env.IMAGE }} 2 3`
            - Status: Success
